api/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views
app_name = 'api'

urlpatterns = [

    # API
    path('', views.ProductListAPI.as_view(), name='api-menu'),
    path('product/<int:pk>/', views.ProductAPI.as_view(), name='api-product'),
    path('product/list/', views.ProductListAPI.as_view(), name='api-product-list'),
    path('category/list/', views.CategoryListAPI.as_view(), name='api-category-list'),
    path('category/<int:pk>/', views.CategoryAPI.as_view(), name='api-category'),

    # Table
    path('table/view/list/', views.TableViewListAPI.as_view(), name='api-table-view-list'),
    path('table/view/<int:pk>/', views.TableViewAPI.as_view(), name='api-table-view'),

    path('table/people/count/list/', views.TableCountListAPI.as_view(), name='api-table-people-count-list'),
    path('table/people/count/<int:pk>/', views.TableCountAPI.as_view(), name='api-table-people-count'),

    path('table/time/list/', views.TableTimeListAPI.as_view(), name='api-table-time-list'),
    path('table/time/<int:pk>/', views.TableTimeAPI.as_view(), name='api-table-time'),

    # Book Table
    path('table/book/', views.BookTableAPI.as_view(), name='api-table-book'),
    path('booked/table/list/', views.BookedTableListAPIView.as_view(), name='api-book-table-list'),

    # Remove Table
    path('table/remove/', views.RemoveTableOrderAPI.as_view(), name='api-table-remove'),


    # Order API
    path('cart/', views.CartListAPI.as_view(), name='api-cart-list'),
    path('add_to_cart/<slug>/', views.AddToCartAPI.as_view(), name='api-add-to-cart'),
    path('cart/<int:cart_pk>/<int:qty>/',
         views.CartQuantityUpdateAPI.as_view(), name='api-cart-qty-update'),
    path('cart/total/<int:pk>/',
         views.CartTotalAPI.as_view(), name='api-cart-total'),
    path('cart/detail/<int:pk>/',
         views.CartDetailAPI.as_view(), name='api-cart-detail'),

    # Order
    path('list/', views.OrderListAPI.as_view(), name='api-list'),
    path('detail/<int:pk>/', views.OrderDetailAPI.as_view(), name='api-detail'),
    path('order/total/', views.OrderTotalAPI.as_view(), name='api-total'),

    # Cancel Order
    path('cancel/<int:pk>/', views.CancelOrderAPI.as_view(),
         name='api-cancel-order'),
    # Cancel Reason
    path('cancel/reason/', views.OrderCancelReasonAPI.as_view(),
         name='api-cancel-reason'),

    # Coupon
    path('coupon/', views.AddCouponOrderAPI.as_view(), name='api-coupon-order'),

    # Checkout
    path('checkout/', views.CheckoutAPI.as_view(), name='api-checkout'),
    path('payment/<int:pk>/', views.PaymentDetailAPI.as_view(),
         name='api-payment-detail'),

    path('register/', views.RegisterAPI.as_view(), name='api-register'),
    path('login/', views.LoginAPI.as_view(), name='api-login'),

    # Update
    path('user/update/', views.UpdateUpdateAPI.as_view(), name='api-update'),

    # Username Verification
    path('resend-confirmation/<str:email>/', views.ResendEmailConfirmationAPI.as_view(),
         name='api-resend-username-confirmation'),

    # Password
    path('password/change/', views.ChangePasswordAPI.as_view(), name='api-password-change'),
    path('password/reset/', include('django_rest_passwordreset.urls', namespace='api-password-reset')),



    path('order/response/', views.RazorPayResponseView.as_view(), name='api-order-payment-response'),


    path('room/booked/<int:pk>/', views.BookRoomAPI.as_view(), name='api-book-room'),
    path('room/list/', views.RoomListAPI.as_view(), name='api-room-list'),
    path('room/response/', views.PaymentAPIView.as_view(), name='api-payment-response'),
    path('room/booked/list/', views.BookedRoomListViewAPI.as_view(), name='api-booked-room-list'),
    path('room/confirmed/booked/list/', views.ConfirmedBookRoomListView.as_view(), name='api-confirmed-book-room-list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golden_nest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('letsmanagestuff/', admin.site.urls),
    path('user/', include('users.urls')),
    path('api/', include('api.urls')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('order/', include('order.urls', namespace='order')),
    path('room/', include('room.urls', namespace='room')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('', include('home.urls', namespace='home')),
]


home/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    
    path('franchise/', TemplateView.as_view(template_name='home/franchise.html'), name='franchise'),

    path('policy/<str:page_name>/', views.Terms.as_view(), name='terms'),
    path('sitemap.xml/', TemplateView.as_view(template_name='home/sitemap.html'), name='sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name='home/robots.html'), name='robots'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone, dateformat
from datetime import timedelta, datetime
from ckeditor.fields import RichTextField


class RestaurantsTiming(models.Model):
    opening_time = models.TimeField()
    closing_time = models.TimeField()

    def __str__(self):
        return f"Restaurants Timing"

    def is_restaurant_open(self):
        now = datetime.now()
        now = now.strftime('%H:%M:%S')
        return self.opening_time.strftime('%H:%M:%S') < now < self.closing_time.strftime('%H:%M:%S')



class TPP(models.Model):
    tand_c = RichTextField(null=True, blank=True)
    shipping_policy = RichTextField(null=True, blank=True)
    refund_policy = RichTextField(null=True, blank=True)
    return_policy = RichTextField(null=True, blank=True)
    cancellation_policy = RichTextField(null=True, blank=True)
    privacy_policy = RichTextField(null=True, blank=True)

    def __str__(self):
        return 'TPP'


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    mobile = models.BigIntegerField()
    description = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.name}_{self.mobile}"


class UpcomingEvent(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{ self.title }"

home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView
from .models import Contact, TPP, UpcomingEvent
from menu.models import Product, Category

class Home(View):
    def get(self, *args, **kwargs):
        event = UpcomingEvent.objects.all()
        first_class = Product.objects.filter(first_class = True, is_active = True)
        category_list = Category.objects.filter(is_active=True)
        context = {
            'event' : event,
            'first_class' : first_class,
            'category' : category_list
        }
        return render(self.request, 'home/home.html', context)


class ContactView(CreateView):
    model = Contact
    fields = ['name', 'email', 'mobile', 'description']
    template_name = "home/contact.html"
    success_url = '/contact/'

    def form_valid(self, form):
        phone_number = form.cleaned_data['mobile']
        if len(str(phone_number)) != 10:
            messages.warning(self.request, 'Invalid mobile number')
            return redirect('home:contact')
        messages.success(self.request, "Message submitted, We will get back to you soon!")
        return super().form_valid(form)


class Terms(View):
    def get(self, *args, **kwargs):
        page_name = self.kwargs.get('page_name')
        tpp = TPP.objects.all().first()
        if page_name == 'terms-and-condition':
            tpp = tpp.tand_c
        elif page_name == 'shiping-policy':
            tpp = tpp.shipping_policy
        elif page_name == 'refund-policy':
            tpp = tpp.refund_policy
        elif page_name == 'return-policy':
            tpp = tpp.return_policy
        elif page_name == 'cancellation-policy':
            tpp = tpp.cancellation_policy
        elif page_name == 'privacy-policy':
            tpp = tpp.privacy_policy
        return render(self.request, 'home/terms_and_condition.html', {'tpp': tpp, 'page': page_name})

home/templates/home/contact.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="content">
        <section class=" no-padding dark-bg hidden-section">
            <div class="map-container">
                <div id="singleMap"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3725.085538860338!2d75.56227521432776!3d20.989207994504717!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bd90f61752cb785%3A0x2a18a8095f0d3033!2sGolden%20Nest!5e0!3m2!1sen!2sin!4v1632315233479!5m2!1sen!2sin" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe></div>
                <div class="scrollContorl"></div>
            </div>
            <!-- map-view-wrap -->
            <div class="map-view-wrap hide-mobile">
                <div class="container">
                    <div class="map-view-wrap_item">
                        <div class="contact-details">
                            <h4>Contacts Details</h4>
                            <ul>
                                <li><span><i class="fal fa-map-marked-alt"></i> Address :</span> <a href="#">Plot no 11, Muhadi Phata, Jalgaon.</a></li>
                                <li><span><i class="fal fa-phone-rotary"></i> Phone :</span> <a href="#">+91 9823333373 ,</a></li>
                                <li><span><i class="fal fa-mailbox"></i> Mail :</span> <a href="#">info@goldennest.in</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--map-view-wrap end -->
            <div class="brush-dec"></div>
        </section>
        <!--  section  -->
        <section class="hidden-section big-padding con-sec" data-scrollax-parent="true" id="sec3">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">


                <div class="container show-mobile-only" style="margin-bottom: 6em;">
                    <div class="map-view-wrap_item">
                        <div class="contact-details" style="color: #fff;">
                            <h4 style="color: #fff !important;">Contacts Details</h4>
                            <ul>
                                <li><span><i class="fal fa-map-marked-alt"></i> Adress :</span> <a href="#">Plot no 11, Muhadi Phata, Jalgaon.</a></li>
                                <li><span><i class="fal fa-phone-rotary"></i> Phone :</span> <a href="#">+91 9823333373 ,</a></li>
                                <li><span><i class="fal fa-mailbox"></i> Mail :</span> <a href="#">info@goldennest.in</a></li>
                            </ul>
                        </div>
                    </div>
                </div>



                        <div class="section-title text-align_left">
                            <h2>Get in touch</h2>
                            <div class="dots-separator fl-wrap"><span></span></div>
                        </div>
                        <div class="text-block ">
<!--                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam aperiam. Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt.-->
<!--                            </p>-->
                        </div>
                        <div class="contactform-wrap">
                            <div id="message"></div>
                            <form  class="custom-form" method="post">
                                {% csrf_token %}
                                <fieldset>
                                <div id="message2"></div>
                                    <div class="row">
                                        <div style="z-index: 9999;" class="col-sm-12">
                                            <input type="text" name="name" id="id_name" placeholder="Your Name *" value=""/>
                                        </div>
                                        <div style="z-index: 9998;" class="col-sm-6">
                                            <input type="text"  name="email" id="id_email" placeholder="Email Address *" value=""/>
                                        </div>
                                        <div class="col-sm-6">
                                            <input type="tel"  name="mobile" id="id_mobile" placeholder="Phone *" pattern="[789][0-9]{9}" value="" style="padding: 1.2em 1.5em;background: rgba(255,255,255,0.1);;width: 100%;border: 0px;color: white;"/>
                                        </div>
                                    </div>
                                    <textarea name="description"  id="id_description" cols="40" rows="3" placeholder="Your Message:"></textarea>
                                    <div class="clearfix"></div>
                                    <button class="btn float-btn flat-btn color-bg" id="submit_cnt">Send Message <i class="fal fa-long-arrow-right"></i></button>
                                </fieldset>
                            </form>
                        </div>
                        <div class="section-dec sec-dec_top"></div>
                    </div>
                    <br><br>
                    <div class="col-md-5">
                        <div class="column-text_inside fl-wrap dark-bg" >
                            <div class="column-text">
                                <div class="section-title">
                                    <h4>Call For Reservations</h4>
                                    <h2>Opening Hours</h2>
                                    <div class="dots-separator fl-wrap"><span></span></div>
                                </div>
                                <div class="work-time fl-wrap">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <h3>Sunday to Tuesday</h3>
                                            <div class="hours">
                                                09:00<br>
                                                22:00
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <h3>Friday to Saturday</h3>
                                            <div class="hours">
                                                11:00<br>
                                                19:00
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="bold-separator"><span></span></div>
                                <div class="big-number"><a href="#">+7(111)123456789</a></div>
                            </div>
                            <div class="illustration_bg">
                                <div class="bg"  data-bg="images/bg/dec/6.png"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section-bg">
                <div class="bg"  data-bg="images/bg/dec/section-bg.png"></div>
            </div>
        </section>
        <!--  section end  -->
        <div class="brush-dec2 brush-dec_bottom"></div>
</div>
{% endblock %}

home/templates/home/robots.html
<br>User-agent: * 
<br>Disallow:
<br>Disallow: /siteAdmin/login 
<br>Disallow: /cgi-bin/

home/templates/home/sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="https://industrialjunction.in/">
<url><loc>https://industrialjunction.in/</loc>
</url>
</urlset>

home/templates/home/terms_and_condition.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

 <div class="content">
     <section class="parallax-section hero-section hidden-section" data-scrollax-parent="true">
                    <div class="bg par-elem " data-bg="{% static 'home/images/bg/10.jpg' %}" data-scrollax="properties: { translateY: '30%' }"></div>
                    <div class="overlay"></div>
                    <div class="container">
                        <div class="section-title">
<!--                            <h4>Enjoy your time in our restaurant with pleasure.</h4>-->
                            {% if page == "terms-and-condition" %}
                            <h2 class="section-title">Terms And Condition</h2>
                            {% elif page == "privacy-policy" %}
                            <h2 class="section-title">Privacy Policy</h2>
                            {% elif page == "shiping-policy" %}
                            <h2 class="section-title">Shipping Policy</h2>
                            {% elif page == "refund-policy" %}
                            <h2 class="section-title">Refund Policy</h2>
                            {% elif page == "return-policy" %}
                            <h2 class="section-title">Return Policy</h2>
                            {% elif page == "cancellation-policy" %}
                            <h2 class="section-title">Cancellation Policy</h2>
                            {% endif %}
                            <div class="dots-separator fl-wrap"><span></span></div>
                        </div>
                    </div>
                    <div class="hero-section-scroll">
                        <div class="mousey">
                            <div class="scroller"></div>
                        </div>
                    </div>
                    <div class="brush-dec"></div>
                </section>
                <!--  section  end-->
                <!--  section  -->
                <section class="hidden-section big-padding" data-scrollax-parent="true">
                    <div class="container">
                        <div class="section-title text-align_left">
                        {{tpp|safe}}
                        </div>
                    </div>
                </section>

 </div>


{% endblock %}