analytics/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views

app_name = 'analytics'

urlpatterns = [
    
    path('', views.Overview.as_view(), name="dashboard"),

    path('menu/', views.ProductListView.as_view(), name="menu-list"),
    path('menu/add/', views.ProductAddView.as_view(), name="menu-add"),
    path('menu/update/<int:pk>/',
         views.ProductUpdateView.as_view(), name="menu-update"),
    path('menu/delete/<int:pk>/',
         views.ProductDeleteView.as_view(), name="menu-delete"),

    path('category/', views.CategoryListView.as_view(), name="category-list"),
    path('category/add/', views.CategoryAddView.as_view(), name="category-add"),
    path('category/update/<int:pk>/',
         views.CategoryUpdateView.as_view(), name="category-update"),
    path('category/delete/<int:pk>/',
         views.CategoryDeleteView.as_view(), name="category-delete"),

    path('coupon/', views.CouponListView.as_view(), name="coupon-list"),
    path('coupon/add/', views.CouponAddView.as_view(), name="coupon-add"),
    path('coupon/update/<int:pk>/',
         views.CouponUpdateView.as_view(), name="coupon-update"),
    path('coupon/delete/<int:pk>/',
         views.CouponDeleteView.as_view(), name="coupon-delete"),

    path('contact/', views.ContactListView.as_view(), name="contact"),
    path('contact/seen/<int:pk>/',
         views.ContactSeenUpdateView.as_view(), name='contact-seen'),
    path('contact/delete/<int:pk>/', views.ContactDeleteView.as_view(), name='contact-delete'),
    # Orders
    path('order/', views.OrderListView.as_view(), name='order-list'),
    path('order/detail/<int:pk>/',
         views.OrderDetailView.as_view(), name='order-detail'),
    path('order/update/<int:pk>/<str:order_status>/',
         views.OrderStatusUpdateView.as_view(), name='order-update'),
    path('order/seen/<int:pk>/',
         views.OrderSeenUpdateView.as_view(), name='order-seen'),

    # OfflineOrders
    path('offline/order/', views.OfflineOrderListView.as_view(), name='offline-order-list'),
    path('offline/order/detail/<int:pk>/',
         views.OfflineOrderDetailView.as_view(), name='offline-order-detail'),
    path('offline/order/update/<int:pk>/<str:order_status>/',
         views.OfflineOrderStatusUpdateView.as_view(), name='offline-order-update'),
    path('offline/order/seen/<int:pk>/',
         views.OfflineOrderSeenUpdateView.as_view(), name='offline-order-seen'),

    # TableReservation
    path('reservations/', views.TableReserveListView.as_view(),
         name='table-reservation-list'),
    path('table/seen/<int:pk>/',
         views.TableReservationSeenUpdateView.as_view(), name='table-seen-update'),
    path('room/seen/<int:pk>/',
         views.RoomSeenUpdateView.as_view(), name='room-seen-update'),

    # Room
    path('room/list/', views.BookedRoomListView.as_view(), name='booked-room-list'),
    path('room/detail/<int:pk>/',
         views.RoomDetailView.as_view(), name='room-detail'),
    path('room/checkout/done/<int:pk>/', views.RoomCheckout.as_view(), name='room-checkout-done'),

    path('room/not/confirmed/list/', views.NotConfirmRoomBookingList.as_view(),
         name='not-confirmed-rooms-list'),
    path('room/confirm/<int:pk>/', views.ConfirmRoomBooking.as_view(),
         name='confirm-room-booking'),

    path('table/not/confirmed/list/', views.NotConfirmTableReservationList.as_view(),
         name='not-confirmed-table-list'),
    path('table/confirm/<int:pk>/', views.ConfirmTableReservation.as_view(),
         name='confirm-table-booking'),

    # RoomReview
    path('review/list/', views.ReviewListView.as_view(), name='review-list'),
    path('review/approve/<int:pk>/',
         views.ReviewApproveView.as_view(), name='review_approve'),
    path('review/seen/<int:pk>/',
         views.ReviewSeenUpdateView.as_view(), name='review-seen'),
    path('review/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review-delete'),

    path('book/table/', views.BookTableAdmin.as_view(), name='admin-book-table'),
    path('check/book/table/', views.check_table_available,
         name='admin-check-table-available'),

    path('book/room/', views.BookRoomAdmin.as_view(), name='admin-book-room'),
    path('check/room/available/', views.check_room_available,
         name='admin-check-room-available'),

    path('overview/', views.Overview.as_view(), name='overview'),
    path('cancel/table/<int:pk>/', views.RejectTableReservation.as_view(), name='reject-table-reservation'),
    path('cancel/room/<int:pk>/', views.RejectRoomBooking.as_view(), name='reject-room-booking'),

    path('generate/qr/<int:pk>/', views.GenerateQrCodeView.as_view(), name='generate-qr'),

    path('ajax_notification/', views.NotificationCheck.as_view(), name="ajax-notification"),

    path('table/list/', views.TableListView.as_view(), name='table-list'),
    path('table/create/', views.TableCreateView.as_view(), name='table-create'),
    path('table/detail/<int:pk>/', views.TableDetailView.as_view(), name='table-detail'),
    path('table/update/<int:pk>/', views.TableUpdateView.as_view(), name='table-update'),
    path('table/delete/<int:pk>/', views.TableDeleteView.as_view(), name='table-delete'),


    path('rooms/list/', views.RoomsListView.as_view(), name='rooms-list'),
    path('rooms/create/', views.RoomsCreateView.as_view(), name='rooms-create'),
    path('rooms/detail/<int:pk>/', views.RoomsDetailView.as_view(), name='rooms-detail'),
    path('rooms/update/<int:pk>/', views.RoomsUpdateView.as_view(), name='rooms-update'),
    path('rooms/delete/<int:pk>/', views.RoomsDeleteView.as_view(), name='rooms-delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views
app_name = 'api'

urlpatterns = [

    # API
    path('', views.ProductListAPI.as_view(), name='api-menu'),
    path('product/<int:pk>/', views.ProductAPI.as_view(), name='api-product'),
    path('product/list/', views.ProductListAPI.as_view(), name='api-product-list'),
    path('category/list/', views.CategoryListAPI.as_view(), name='api-category-list'),
    path('category/<int:pk>/', views.CategoryAPI.as_view(), name='api-category'),

    # Table
    path('table/view/list/', views.TableViewListAPI.as_view(), name='api-table-view-list'),
    path('table/view/<int:pk>/', views.TableViewAPI.as_view(), name='api-table-view'),

    path('table/people/count/list/', views.TableCountListAPI.as_view(), name='api-table-people-count-list'),
    path('table/people/count/<int:pk>/', views.TableCountAPI.as_view(), name='api-table-people-count'),

    path('table/time/list/', views.TableTimeListAPI.as_view(), name='api-table-time-list'),
    path('table/time/<int:pk>/', views.TableTimeAPI.as_view(), name='api-table-time'),

    # Book Table
    path('table/book/', views.BookTableAPI.as_view(), name='api-table-book'),
    path('booked/table/list/', views.BookedTableListAPIView.as_view(), name='api-book-table-list'),

    # Remove Table
    path('table/remove/', views.RemoveTableOrderAPI.as_view(), name='api-table-remove'),


    # Order API
    path('cart/', views.CartListAPI.as_view(), name='api-cart-list'),
    path('add_to_cart/<slug>/', views.AddToCartAPI.as_view(), name='api-add-to-cart'),
    path('cart/<int:cart_pk>/<int:qty>/',
         views.CartQuantityUpdateAPI.as_view(), name='api-cart-qty-update'),
    path('cart/total/<int:pk>/',
         views.CartTotalAPI.as_view(), name='api-cart-total'),
    path('cart/detail/<int:pk>/',
         views.CartDetailAPI.as_view(), name='api-cart-detail'),

    # Order
    path('list/', views.OrderListAPI.as_view(), name='api-list'),
    path('detail/<int:pk>/', views.OrderDetailAPI.as_view(), name='api-detail'),
    path('order/total/', views.OrderTotalAPI.as_view(), name='api-total'),

    # Cancel Order
    path('cancel/<int:pk>/', views.CancelOrderAPI.as_view(),
         name='api-cancel-order'),
    # Cancel Reason
    path('cancel/reason/', views.OrderCancelReasonAPI.as_view(),
         name='api-cancel-reason'),

    # Coupon
    path('coupon/', views.AddCouponOrderAPI.as_view(), name='api-coupon-order'),

    # Checkout
    path('checkout/', views.CheckoutAPI.as_view(), name='api-checkout'),
    path('payment/<int:pk>/', views.PaymentDetailAPI.as_view(),
         name='api-payment-detail'),

    path('register/', views.RegisterAPI.as_view(), name='api-register'),
    path('login/', views.LoginAPI.as_view(), name='api-login'),

    # Update
    path('user/update/', views.UpdateUpdateAPI.as_view(), name='api-update'),

    # Username Verification
    path('resend-confirmation/<str:email>/', views.ResendEmailConfirmationAPI.as_view(),
         name='api-resend-username-confirmation'),

    # Password
    path('password/change/', views.ChangePasswordAPI.as_view(), name='api-password-change'),
    path('password/reset/', include('django_rest_passwordreset.urls', namespace='api-password-reset')),



    path('order/response/', views.RazorPayResponseView.as_view(), name='api-order-payment-response'),


    path('room/booked/<int:pk>/', views.BookRoomAPI.as_view(), name='api-book-room'),
    path('room/list/', views.RoomListAPI.as_view(), name='api-room-list'),
    path('room/response/', views.PaymentAPIView.as_view(), name='api-payment-response'),
    path('room/booked/list/', views.BookedRoomListViewAPI.as_view(), name='api-booked-room-list'),
    path('room/confirmed/booked/list/', views.ConfirmedBookRoomListView.as_view(), name='api-confirmed-book-room-list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golden_nest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('letsmanagestuff/', admin.site.urls),
    path('user/', include('users.urls')),
    path('api/', include('api.urls')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('order/', include('order.urls', namespace='order')),
    path('room/', include('room.urls', namespace='room')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('', include('home.urls', namespace='home')),
]


analytics/models.py
from django.db import models

# Create your models here.

analytics/forms.py
from django import forms
from menu.models import BookTable, Table, TableTime
from room.models import RoomBooked, Rooms


class AdminTableBookForm(forms.ModelForm):
    class Meta:
        model = BookTable
        fields = ['table', 'name', 'email', 'phone_number', 'people_count', 'sitting_type', 'booked_for_time',
                  'booked_for_date',
                  ]
        widgets = {
            'booked_for_date': forms.DateInput(format='%d-%m-%Y',
                                               attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                      'type': 'date'}),
            'booked_for_time': forms.DateInput(format='%H:%M:%S',
                                               attrs={'class': 'form-control', 'placeholder': 'Select a Time',
                                                      'type': 'time'}),
        }


class AdminRoomBookForm(forms.ModelForm):
    class Meta:
        model = RoomBooked
        fields = ('name', 'phone_number', 'room_type', 'check_in', 'check_out')
        widgets = {
            'check_in': forms.DateInput(format='%d-%m-%Y',
                                        attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                               'type': 'date'}),
            'check_out': forms.DateInput(format='%d-%m-%Y',
                                         attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                'type': 'date'}),
        }


class TableCreateForm(forms.ModelForm):
    class Meta:
        model = Table
        exclude = ['slug','date_added','qr_code']

class RoomsCreateForm(forms.ModelForm):
    class Meta:
        model = Rooms
        fields = '__all__'

analytics/templates/analytics/category_add_update.html
{% extends "analytics/base.html" %}
{% load crispy_forms_tags %}
{% block nav-category %}style="color: #FFB319;"{% endblock %}
{% block data %}

<style>
    .cke_inner cke_reset{
       width: 50%;
    }
</style>


<div class="row bg-white p-4" style="border-radius: 0.5em;">
    <div class="col-12">
        {% if request.path == "/analytics/category/add/" %}
        <h3 align="center" style="font-weight: bold;">Create Category</h3><hr>
        {% else %}
        <h3 align="center" style="font-weight: bold;">Update Category</h3><hr>
        {% endif %}
    </div>
    <div class="col-lg-12">
       <form class="row" method="post">
          {% csrf_token %}
         <div class="col-lg-12 pb-3">
            {{ form.title|as_crispy_field }}
         </div>
         <div class="col-lg-12 pb-3">
            {{ form.image|as_crispy_field }}
         </div>
         <div class="col-lg-6 pb-3">
            {{ form.is_active|as_crispy_field }}
         </div>
         <div class="col-lg-12 pb-3">
             {% if request.path == "/analytics/category/add/" %}
             <button class="btn btn-info w-100">ADD CATEGORY</button>
             {% else %}
             <button class="btn btn-info w-100">UPDATE CATEGORY</button>
             {% endif %}
         </div>
       </form>
    </div>
</div>

{% endblock data %}

analytics/templates/analytics/order_list.html
{% extends "analytics/base.html" %} 

{% block data %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<style>
	#contact-table {
		background: #fff;
	}

    .rounded-circle {
		width: 26px;
		height: 26px;
		padding: 2px;
		text-align: center;
		font-size: 12px;
	}

	.card {
		display: block;
		padding: 1em;
        padding-top: 0;
        font-family: 'Open Sans', sans-serif;
	}

    .card-body {
        padding: 1em 2.8em 0 0;
        margin: 0;
        width: 100%;
    }

    .th-head {
        border: none !important; 
        font-weight: 600; 
        text-transform: uppercase;
        font-size: 0.9em;
        vertical-align: top !important;
    }

    table td, table td * {
        vertical-align: top !important;
    }

</style>


{% for object in object_list %}
<div style="border-radius: 0.5em; border-color: #fff;" class="card mb-4  pb-1 container">
    <div class="bg-white card-header d-block row">
        <div class="pt-0 py-2">
            <div>
            {% if not 'offline/order/' in request.path %}
            <a href="{% url 'analytics:order-detail' object.pk %}" style="font-weight: 700; color: rgb(0, 0, 0); " class="float-left">#{{object.order_ref_number}}</a>
            <a style="color:rgb(25, 79, 255)" class="m-2 font-weight-bold" href="{% url 'analytics:order-seen' object.pk %}">
            {% else %}
                <a href="{% url 'analytics:offline-order-detail' object.pk %}" style="font-weight: 700; color: rgb(0, 0, 0); " class="float-left">#{{object.order_ref_number}}</a>
                <a style="color:rgb(25, 79, 255)" class="m-2 font-weight-bold" href="{% url 'analytics:offline-order-seen' object.pk %}">
            {% endif %}
                {% if object.seen %}
                <i class="fas fa-check"></i>
                {% else %}
                <i class="fas fa-eye"></i>
                {% endif %}
            </a>
            </div>


            <div class="ml-3" style="float:right; transform: translateY(-25px);">
                {% if not 'offline/order/' in request.path %}
                <a class="btn btn-outline-warning mr-2 font-weight-bold"
                    href="{% url 'analytics:order-detail' object.pk %}">
                    <i class="fas fa-cog"></i> Manage
                </a>

                {% else %}
                <a class="btn btn-outline-warning mr-2 font-weight-bold"
                    href="{% url 'analytics:offline-order-detail' object.pk %}">
                    <i class="fas fa-cog"></i> Manage
                </a>
                {% endif %}

            </div>

        <!-- {% if object.table %}
            <div class="col-12 col-md-3 pr-0" align="right" style="float:right; transform: translateY(-25px);">
            {% if object.table.is_confirmed %}
                <a style="color:rgb(255, 176, 58)" class="m-2 mr-0 font-weight-bold"
                    href="{% url 'analytics:table-reservation-list' %}">
                    View Table
                </a>
            {% else %}
                <a style="color:rgb(255, 176, 58)" class="m-2 mr-0 font-weight-bold"
                    href="{% url 'analytics:not-confirmed-table-list' %}">
                    View Table
                </a>
            {% endif %}
            </div>
        {% endif %} -->
        </div>
    </div>

    <div class="card-body row pt-4">  
        {% if '/offline/' in request.path %}
        <div class="col-lg-4 col-md-6 mb-3">
            <div class="bg-white p-3" style="border-radius: 0.5em;">
                <div class="row mb-2">
                    <h6 class="font-weight-bold" style="text-transform: capitalize;font-size: 0.9em;">Table No.</h6>                        
                </div>
                <div class="row">
                    <p style="font-weight: 700;">{{object.table}}</p>                        
                </div>
                
            </div>
        </div>
        {% else %}
        <div class="col-lg-4 col-md-6 mb-3">
            <div class="bg-white p-3" style="border-radius: 0.5em;">
                <div class="row mb-2">
                    <h6 class="font-weight-bold" style="text-transform: capitalize;font-size: 0.9em;">Date</h6>                        
                </div>
                <div class="row">
                    <p style="font-weight: 700;">{{object.ordered_date_time}}</p>                        
                </div>
                
            </div>
        </div>
        {% endif %}

        <div class="col-lg-4 col-md-6 mb-3">
            <div class="bg-white p-3" style="border-radius: 0.5em;">
                <div class="row mb-2">
                    <h6 class="font-weight-bold" style="text-transform: capitalize;font-size: 0.9em;">Status</h6>                        
                </div>
                <div class="row">
                    {% if object.order_status == 'Delivered' %}
                        <p class="" style="color: rgb(75, 189, 0); font-weight: 700;">{{object.order_status}}</p>
                    {% elif object.order_status == 'CANCELED' %}
                        <p class="" style="color: rgb(248, 70, 0); font-weight: 700;">{{object.order_status}}</p>
                    {% else %}
                        <p class="" style="color: rgb(230, 149, 0); font-weight: 700;">{{object.order_status}}</p>
                    {% endif %}                        
                </div>
                
            </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-3">
            <div class="bg-white p-3" style="border-radius: 0.5em;">
                <div class="row mb-2">
                    <h6 class="font-weight-bold" style="text-transform: capitalize;font-size: 0.9em;">Ordered Item</h6>                        
                </div>
                <div class="row">
                    <p style="font-weight: 700;">{{object.cart.all.count}}</p>                   
                </div>
                
            </div>
        </div>

        <div class="col-lg-1 col-md-6 mb-3">
            <div class="bg-white p-3" style="border-radius: 0.5em;">
                <div class="row mb-2">
                    <h6 class="font-weight-bold" style="text-transform: capitalize;font-size: 0.9em;">Amount</h6>                        
                </div>
                <div class="row">
                    <p style="font-weight: 700;">₹{{object.get_total}}</p>                   
                </div>
                
            </div>
        </div>

        
        </div>
    </div>

{% endfor %}




<div class="d-flex justify-content-center m-4">
	{% if is_paginated %}
	
		  {% if page_obj.has_previous %}
			<a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page=1">&lt;&lt;</a>
			<a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.previous_page_number}}">&lt;</a>
		  {% endif %}
	
		  {% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
			  <a class="btn btn-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{num}}">{{num}}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
			<a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{num}}">{{num}}</a>
			{% endif %}
		  {% endfor %}
	
		  {% if page_obj.has_next %}
			<a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.next_page_number}}">&gt;</a>
			<a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.paginator.num_pages}}">&gt;&gt;</a>
		  {% endif %}
	
	{% endif %}
</div>


{% endblock data %}

analytics/templates/analytics/rooms_list.html
{% extends "analytics/base.html" %}
{% load crispy_forms_tags %}
{% block nav-room %}style="color: #FFB319;"{% endblock %}
{% block data %}

<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">

<style>

    * {
        font-family: 'Manrope', sans-serif;
    }

	

	

</style>

<div style="border-radius: 0.5em;" class="border-0 p-3 mx-3 mb-4 row bg-white">
	<h3 class="text-dark pl-3 col-6" style="font-weight:600; font-family: 'Manrope', sans-serif;">All Rooms</h3>
	<div class="col-6">
		<a style="background-color: #1F3BB3; font-family: 'Manrope', sans-serif;" class="btn btn-primary float-right" href="{% url 'analytics:rooms-create' %}"><i class="fas fa-plus"></i>&nbsp; Add Room</a>
	</div>
	
</div>


<div class="row col-12 m-0 p-0">
{% for object in object_list %}
	<div style="border-radius: 0.5em;" class="col-lg-6 m-0 my-3">
	<div class="bg-white border-0 card p-3">


		<h3 align="center" class="py-2 font-weight-bold">{{object.name}}</h3><hr>
	
		<div class="">
			<div id="carouselExampleControls{{object.id}}" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
				  	<div class="carousel-item active">
					  <img src="{{object.image_main.url}}" class="d-block col-md-12" alt="...">
					</div>

					  {% if object.image_2 %}
					  <div class="carousel-item">
						  <img src="{{object.image_2.url}}" class="d-block col-md-12" alt="...">
					  </div>
						
					  {% endif %}
					
				  
				  	{% if object.image_3 %}
				  	<div class="carousel-item">
					  <img src="{{object.image_3.url}}" class="d-block col-md-12" alt="...">
					</div>
					{% endif %}
					{% if object.image_4 %}
					<div class="carousel-item">
						<img src="{{object.image_4.url}}" class="d-block col-md-12" alt="...">
					</div>
				  	{% endif %}
				  
				  
				  
					  {% if object.image_5 %}
					  <div class="carousel-item">
						  <img src="{{object.image_5.url}}" class="d-block col-md-12" alt="...">
					  </div>
					{% endif %}

					{% if object.image_6 %}
					<div class="carousel-item">
						<img src="{{object.image_6.url}}" class="d-block col-md-12" alt="...">
					</div>
				  	{% endif %}
				  
	
				  
				</div>
				<a class="carousel-control-prev" href="#carouselExampleControls{{object.id}}" role="button" data-slide="prev">
				  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				  <span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleControls{{object.id}}" role="button" data-slide="next">
				  <span class="carousel-control-next-icon" aria-hidden="true"></span>
				  <span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	
		<br><br>
	
		<div class="row border-bottom py-3 mx-2">
			<div class="col-lg-12">
				<span><strong>Stock Number</strong>: &nbsp;{{ object.stock_no }}</span>
			</div>
		</div>
		
		<div class="row border-bottom py-3 mx-2">
			<div class="col-lg-12">
				<span><strong>Price</strong> &nbsp;{{ object.price }}</span>
			</div>
		</div>
		<div class="row border-bottom py-3 mx-2">
			<div class="col-lg-12">
				<span><strong>Description</strong> &nbsp;{{ object.short_description }}</span>
			</div>
		</div>
		
	
	
		<div class="row p-2">
			<p class="mt-5 col-sm-4 col-6 text-center">
				<a class="btn btn-outline-primary" href="{% url 'analytics:rooms-detail' object.id %}"><i class="fas fa-info-circle"></i>&nbsp;&nbsp;Details</a>
			</p>

			<p class="mt-5 col-sm-4 col-6 text-center">
				<a class="btn btn-outline-warning" href="{% url 'analytics:rooms-update' object.id %}"><i class="fas fa-edit"></i>&nbsp;&nbsp;Edit</a>
			</p>
			<p class="mt-5 col-sm-4 col-6 text-center">
				<a class="btn btn-outline-danger" href="{% url 'analytics:rooms-delete' object.id %}"><i class="fas fa-trash-alt"></i>&nbsp;&nbsp;Delete</a>
			</p>
	  </div>
		
	
	</div>
	</div>
	{% endfor %}
</div>


<div class="d-flex justify-content-center m-4">
{% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page=1">&lt;&lt;</a>
        <a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.previous_page_number}}">&lt;</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{num}}">{{num}}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{num}}">{{num}}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.next_page_number}}">&gt;</a>
        <a class="btn btn-outline-info m-1 mb-4 rounded-circle d-flex justify-content-center align-items-center" href="?page={{page_obj.paginator.num_pages}}">&gt;&gt;</a>
      {% endif %}

{% endif %}
</div>

{% endblock %}