api/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views
app_name = 'api'

urlpatterns = [

    # API
    path('', views.ProductListAPI.as_view(), name='api-menu'),
    path('product/<int:pk>/', views.ProductAPI.as_view(), name='api-product'),
    path('product/list/', views.ProductListAPI.as_view(), name='api-product-list'),
    path('category/list/', views.CategoryListAPI.as_view(), name='api-category-list'),
    path('category/<int:pk>/', views.CategoryAPI.as_view(), name='api-category'),

    # Table
    path('table/view/list/', views.TableViewListAPI.as_view(), name='api-table-view-list'),
    path('table/view/<int:pk>/', views.TableViewAPI.as_view(), name='api-table-view'),

    path('table/people/count/list/', views.TableCountListAPI.as_view(), name='api-table-people-count-list'),
    path('table/people/count/<int:pk>/', views.TableCountAPI.as_view(), name='api-table-people-count'),

    path('table/time/list/', views.TableTimeListAPI.as_view(), name='api-table-time-list'),
    path('table/time/<int:pk>/', views.TableTimeAPI.as_view(), name='api-table-time'),

    # Book Table
    path('table/book/', views.BookTableAPI.as_view(), name='api-table-book'),
    path('booked/table/list/', views.BookedTableListAPIView.as_view(), name='api-book-table-list'),

    # Remove Table
    path('table/remove/', views.RemoveTableOrderAPI.as_view(), name='api-table-remove'),


    # Order API
    path('cart/', views.CartListAPI.as_view(), name='api-cart-list'),
    path('add_to_cart/<slug>/', views.AddToCartAPI.as_view(), name='api-add-to-cart'),
    path('cart/<int:cart_pk>/<int:qty>/',
         views.CartQuantityUpdateAPI.as_view(), name='api-cart-qty-update'),
    path('cart/total/<int:pk>/',
         views.CartTotalAPI.as_view(), name='api-cart-total'),
    path('cart/detail/<int:pk>/',
         views.CartDetailAPI.as_view(), name='api-cart-detail'),

    # Order
    path('list/', views.OrderListAPI.as_view(), name='api-list'),
    path('detail/<int:pk>/', views.OrderDetailAPI.as_view(), name='api-detail'),
    path('order/total/', views.OrderTotalAPI.as_view(), name='api-total'),

    # Cancel Order
    path('cancel/<int:pk>/', views.CancelOrderAPI.as_view(),
         name='api-cancel-order'),
    # Cancel Reason
    path('cancel/reason/', views.OrderCancelReasonAPI.as_view(),
         name='api-cancel-reason'),

    # Coupon
    path('coupon/', views.AddCouponOrderAPI.as_view(), name='api-coupon-order'),

    # Checkout
    path('checkout/', views.CheckoutAPI.as_view(), name='api-checkout'),
    path('payment/<int:pk>/', views.PaymentDetailAPI.as_view(),
         name='api-payment-detail'),

    path('register/', views.RegisterAPI.as_view(), name='api-register'),
    path('login/', views.LoginAPI.as_view(), name='api-login'),

    # Update
    path('user/update/', views.UpdateUpdateAPI.as_view(), name='api-update'),

    # Username Verification
    path('resend-confirmation/<str:email>/', views.ResendEmailConfirmationAPI.as_view(),
         name='api-resend-username-confirmation'),

    # Password
    path('password/change/', views.ChangePasswordAPI.as_view(), name='api-password-change'),
    path('password/reset/', include('django_rest_passwordreset.urls', namespace='api-password-reset')),



    path('order/response/', views.RazorPayResponseView.as_view(), name='api-order-payment-response'),


    path('room/booked/<int:pk>/', views.BookRoomAPI.as_view(), name='api-book-room'),
    path('room/list/', views.RoomListAPI.as_view(), name='api-room-list'),
    path('room/response/', views.PaymentAPIView.as_view(), name='api-payment-response'),
    path('room/booked/list/', views.BookedRoomListViewAPI.as_view(), name='api-booked-room-list'),
    path('room/confirmed/booked/list/', views.ConfirmedBookRoomListView.as_view(), name='api-confirmed-book-room-list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golden_nest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('letsmanagestuff/', admin.site.urls),
    path('user/', include('users.urls')),
    path('api/', include('api.urls')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('order/', include('order.urls', namespace='order')),
    path('room/', include('room.urls', namespace='room')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('', include('home.urls', namespace='home')),
]


menu/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from . import api

app_name = 'menu'

urlpatterns = [
    # Menu
    path('', views.MenuListView.as_view(), name='menu'),
    # Book Table
    path('book/table/', views.BookTableView.as_view(), name='book-table'),
    # path('confirmed/booked/table/list/', views.ConfirmBookedTableListView.as_view(), name='booked-table-list'),
    path('booked/table/list/', views.BookedTableListView.as_view(), name='booked-table-list'),

    # Remove Table from order
    path('table/remove/', views.RemoveTableOrder.as_view(), name='remove-table'),

    # Rest Api URL
    # Menu
    path('api/', api.ProductListAPI.as_view(), name='api-menu'),
    path('api/product/<int:pk>/', api.ProductAPI.as_view(), name='api-product'),
    path('api/product/list/', api.ProductListAPI.as_view(), name='api-product-list'),
    path('api/category/list/', api.CategoryListAPI.as_view(), name='api-category-list'),
    path('api/category/<int:pk>/', api.CategoryAPI.as_view(), name='api-category'),

    # Table
    path('api/table/view/list/', api.TableViewListAPI.as_view(), name='api-table-view-list'),
    path('api/table/view/<int:pk>/', api.TableViewAPI.as_view(), name='api-table-view'),

    path('api/table/people/count/list/', api.TableCountListAPI.as_view(), name='api-table-people-count-list'),
    path('api/table/people/count/<int:pk>/', api.TableCountAPI.as_view(), name='api-table-people-count'),

    path('api/table/time/list/', api.TableTimeListAPI.as_view(), name='api-table-time-list'),
    path('api/table/time/<int:pk>/', api.TableTimeAPI.as_view(), name='api-table-time'),

    # Book Table
    path('api/table/book/', api.BookTableAPI.as_view(), name='api-table-book'),

    # Remove Table
    path('api/table/remove/', api.RemoveTableOrderAPI.as_view(), name='api-table-book'),

    path('check/table/available/', views.check_table_available, name='check-table-available'),
    path('cancel/table/booking/', views.CancelTableBeforeDateTime.as_view(), name='cancel-table-booking'),

    path('table/booking/success/<int:pk>/', views.TableBookingSuccessView.as_view(), name='thanks-page'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room/urls.py
from django.urls import path
from . import views

app_name = 'room'
urlpatterns = [
    path('list/', views.RoomListView.as_view(), name='list'),
    path('<int:pk>/', views.RoomDetailView.as_view(), name='book'),
    path('<int:pk>/booked/', views.BookRoomAddView.as_view(), name='book-room'),

    # Review
    path('<int:pk>/review/add', views.ReviewAdd.as_view(), name='review-add'),

    # Booking
    path('booking/', views.RoomBookingList.as_view(), name='booking-list'),

    path('check/room/available/', views.check_room_available, name='check-room-available'),

    path('booking/cancel/', views.RoomBookingCancelView.as_view(), name='room-cancel-booking'),
    path('booking/checkout/', views.RoomBookingCheckoutView.as_view(), name='room-booking-checkout'),
    path('booking/success/<int:pk>/', views.RoomBookingSuccessView.as_view(), name='room-booking-success'),
    path('booked/room/list/', views.BookedRoomListView.as_view(), name='booked-room-list'),
    path('confirmed/booked/room/list/', views.ConfirmedBookedRoomListView.as_view(), name='confirmed-booked-room-list'),
    path('cancel/booking/', views.CancelRoomBookingBeforeCheckin.as_view(), name='cancel-room-booking'),
    path('booking/razorpay/response/', views.RazorPayRoomResponseView.as_view(), name='room-payment-response'),

]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views
from . import api

urlpatterns = [
    # Login and Register
    path('account/<int:pk>/', views.UserUpdateView.as_view(), name='account'),
#     path('account/<int:pk>/', TemplateView.as_view(template_name="users/profile.html"), name='account'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.SignUpView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),

    # Update Username
#     path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),

    # User Username Verification
    path('resend-confirmation/', views.ResendMailConfirmationView.as_view(),
         name='resend-email-confirmation'),
    path('activate/<uidb64>/<token>', views.EmailVerificationView.as_view(), name='activate'),

    # Password
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'),
         name='password_change'),
    path('change-password-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

     



    # Rest Api
    # Login and Register
    path('api/register/', api.RegisterAPI.as_view(), name='api-register'),
    path('api/login/', api.LoginAPI.as_view(), name='api-login'),

    # Update
    path('api/user/update/', api.UpdateUpdateAPI.as_view(), name='api-update'),

    # Username Verification
    path('api/resend-confirmation/<str:email>/', api.ResendEmailConfirmationAPI.as_view(),
         name='api-resend-username-confirmation'),

    # Password
    path('api/password/change/', api.ChangePasswordAPI.as_view(), name='api-password-change'),
    path('api/password/reset/', include('django_rest_passwordreset.urls', namespace='api-password-reset')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from __future__ import unicode_literals
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver
from django_rest_passwordreset.signals import reset_password_token_created
from django.conf import settings
from django.utils import timezone

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('Email'), unique=True, max_length=320, help_text='Provide an email for registration')
    name = models.CharField(_('Name'), max_length=70)
    phone_number = models.BigIntegerField(help_text='Provide an mobile number without +91')  # TODO add validator

    date_confirmation_mail_sent = models.DateTimeField(_('date confirmation mail sent'), default=timezone.now)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=False)
    is_verified = models.BooleanField(_('verified'), default=False)
    is_staff = models.BooleanField(_('staff'), default=False)

    token = models.TextField(_('token'), blank=True, null=True)  # Used in DRF

    objects = UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_number']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("profile")

    def get_full_name(self):
        full_name = '%s %s' % (self.name)
        return full_name.strip()

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # Used in DRF
    @receiver(reset_password_token_created)
    def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
        email_plaintext_message = "{}?token={}".format(reverse('password_reset:reset-password-request'),
                                                       reset_password_token.key)

        send_mail(
            # title:
            "Password Reset for {title}".format(title="Some website title"),
            # message:
            email_plaintext_message,
            # from:
            settings.AUTH_USER_MODEL,
            # to:
            [reset_password_token.user.email]
        )


users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils.translation import gettext_lazy as _

from .models import (User)


class LoginForm(forms.Form):
    email = forms.CharField(label='email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class EmailForm(forms.Form):
    email = forms.CharField(label='email')


class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'name', 'phone_number', 'password1', 'password2')

    def clean(self):
        super(RegistrationForm, self).clean()
        phone_number = self.cleaned_data.get('phone_number')
        if len(str(phone_number)) != 10:
            raise ValidationError(
                _(f'{phone_number} is not an valid mobile number'))


# if inherit form UserChangeForm then user fields are working but also getting password reset form
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'phone_number')

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError(
                _(f'{email} is not an valid email'))

        try:
            email = User.objects.exclude(pk=self.instance.pk).get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('email "%s" is already in use.' % email)


users/templates/users/account_base.html
{% extends 'home/base.html' %}
{% load static %}
{% load order_extras %}
{% block content %}
    <div class="content">
         <!--  section  -->
        <section class="parallax-section hero-section hidden-section" data-scrollax-parent="true">
            <div class="bg par-elem "  data-bg="{% static 'home/images/bg/19.jpg' %}" data-scrollax="properties: { translateY: '30%' }"></div>
            <div class="overlay"></div>
            <div class="container">
                <div class="section-title">
                    <!-- <h4>Enjoy your time in our restaurant with pleasure.</h4> -->
                    <h2>{% block achead %}{% endblock %}</h2>
                    <!-- <h2>Your Profile</h2> -->
                    <div class="dots-separator fl-wrap"><span></span></div>
                </div>
            </div>
            <div class="hero-section-scroll">
                <div class="mousey">
                    <div class="scroller"></div>
                </div>
            </div>
            <div class="brush-dec"></div>
        </section>
        <!--  section  end-->

        <!--  section  -->
        <section class="hidden-section" data-scrollax-parent="true" id="sec2">
            <div class="container">


                <div class="row">
                        <!--  hero-menu_header-->
                        <div class="col-md-3">
                            <div class="cart-totals dark-bg fl-wrap hide-mobile" style="padding: 2em 2em 2em 3em;">
                            <div class="hero-menu_header total-table fl-wrap hide-mobile">
                                <ul class=" no-list-style change_bg">

                                    <li><a href="" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span></span>Hello, {{user.name}}</a></li>
                                    {% if '/account/' in request.get_full_path %}
                                        <li class="current"><a href="{% url 'account' user.pk %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>01.</span>Your Profile</a></li>
                                    {% else %}
                                        <li><a href="{% url 'account' user.pk %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>01.</span>Your Profile</a></li>
                                    {% endif %}
                                    
                                    {% if '/order/' in request.get_full_path %}
                                        <li class="current"><a href="{% url 'order:list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>02.</span>Your Order</a></li>
                                    {% else %}
                                        <li><a href="{% url 'order:list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>02.</span>Your Order</a></li>
                                    {% endif %}

                                    {% if '/room/' in request.get_full_path %}
                                        <li class="current"><a href="{% url 'room:booked-room-list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>03.</span>Your Booking</a></li>
                                    {% else %}
                                        <li><a href="{% url 'room:booked-room-list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>03.</span>Your Booking</a></li>
                                    {% endif %}

                                    {% if '/table/' in request.get_full_path %}
                                        <li class="current"><a href="{% url 'menu:booked-table-list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>04.</span>Your Tables</a></li>
                                    {% else %}
                                        <li><a href="{% url 'menu:booked-table-list' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>04.</span>Your Tables</a></li>
                                    {% endif %}

                                    <li><a href="{% url 'logout' %}" data-bgtab="{% static 'home/images/bg/4.jpg' %}"><span>05.</span>Logout</a></li>

                                </ul>
                            </div>
                            </div>
                        </div>
                        <!--  hero-menu_header  end-->
                        <!--  hero-menu_content   -->
                        <div class="col-md-9">
                            {% block room %}
                            {% endblock room %}
                        </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}

users/templates/users/logout.html
{% extends "home/base.html" %}

{% block content %}
    <div class="content-section">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'users-login' %}">Login Again</a>
            </small>
        </div>
    </div>


{% endblock content %}

users/templates/users/password_change.html


{% extends "users/account_base.html" %}
{% load crispy_forms_tags %}
{% block achead %}Change Password{% endblock %}
{% block data %}
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Change Password</button>
            </div>
        </form>
{% endblock data %}

users/templates/users/password_change_complete.html
{% extends "users/account_base.html" %}

{% block achead %}Password Success{% endblock %}

{% block data %}
    <h2>You have been logged out</h2>
    <div class="alert alert-info">
        Your password has been changed succesfully
    </div>
    <a href="{%url 'users-login' %}">Login Here!</a>
{% endblock data %}

users/templates/users/password_change_done.html
{% extends "users/account_base.html" %}
{% block achead %}Password Changed{% endblock %}

{% block data %}
    <div class="alert alert-info">
        You have successfully changed your password
    </div>
{% endblock data %}

users/templates/users/register.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="content">
        <section class="parallax-section hero-section hidden-section" data-scrollax-parent="true">
            <div class="bg par-elem "  data-bg="images/bg/10.jpg" data-scrollax="properties: { translateY: '30%' }"></div>
            <div class="overlay"></div>
            <div class="container">
                <div class="section-title">
                    <h2>Register</h2>
                    <div class="dots-separator fl-wrap"><span></span></div>
                </div>
            </div>
            <div class="brush-dec"></div>
        </section>
        <!--  section  -->
        

        <section class="hidden-section big-padding con-sec" data-scrollax-parent="true" id="sec3">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="section-title text-align_left">
                                        <h2>Register</h2>
                                        <div class="dots-separator fl-wrap"><span></span></div>
                                    </div>
<!--                                    <div class="text-block ">-->
<!--                                        <p>By creating an account with our store, you will be able to move through the checkout process faster, store shipping addresses, view and track your orders in your account and more.-->
<!--                                        </p>-->
<!--                                    </div>-->
                                    <div class="contactform-wrap">
                                        <div id="message"></div>
                                        <form class="custom-form" method="post" name="registerform" id="registerform">
                                            {% csrf_token %}
                                            <fieldset>
                                            <div id="message2"></div>
                                                <div class="row">
                                                    <div style="z-index: 9999;" class="col-sm-12">
                                                        <input type="text" name="name" id="id_name" placeholder="Your Name *" value="" required/>
                                                    </div>
                                                    <div style="z-index: 9999;" class="col-sm-12">
                                                        <input type="email" name="email" id="id_email" placeholder="Email Address *" value="" required/>
                                                    </div>
                                                    <div class="col-sm-12">
                                                        <input type="tel" name="phone_number" id="id_phone_number" placeholder="Phone *" pattern="[789][0-9]{9}" style="padding: 1.2em 1.5em;background: rgba(255,255,255,0.1);width: 100%;border: 0px;color: white;" value="" required/>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <input type="password" name="password1" id="id_password1" placeholder="Password *" value="" required/>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <input type="password" name="password2" id="id_password2" placeholder="Confirm Password *" value="" required/>
                                                    </div>

                                                     <div class="col-12">
                                                       <button type="submit" class="btn fl-btn" style="margin: 1.2em;">Sign up<i class="fal fa-long-arrow-right"></i></button>
                                                    </div>
                                                    <br><br>
                                                    <div class="col-12" style=" margin: 2em; margin-left: 1.1em;">
                                                        <p align="left" style="display:block; margin-top: 2em; margin-bottom: 2em;font-family: 'Playfair Display', cursive;color: #fff;font-size: 1.1em;float: left;">Already have an account ? <a style="color: #C19D60;" href="{% url 'login' %}"> Sign in </a></p>
                                                    </div>

                                                </div>

                                            </fieldset>
                                        </form>
                                    </div>
                                    <div class="section-dec sec-dec_top"></div>
                                </div>
                                <div class="col-md-5">
                                    <div class="column-text_inside fl-wrap dark-bg" >
                                        <div class="column-text">
                                            <div class="section-title">
                                                <h4>Call For Reservations</h4>
                                                <h2>Opening Hours</h2>
                                                <div class="dots-separator fl-wrap"><span></span></div>
                                            </div>
                                            <div class="work-time fl-wrap">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <h3>Sunday to Tuesday</h3>
                                                        <div class="hours">
                                                            09:00<br>
                                                            22:00
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <h3>Friday to Saturday</h3>
                                                        <div class="hours">
                                                            11:00<br>
                                                            19:00
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="bold-separator"><span></span></div>
                                            <!-- <div class=""><a href="{% url 'login' %}" class="btn fl-btn">Reserve Table <i class="fal fa-long-arrow-right"></i></a></div> -->
                                        </div>
                                        <div class="illustration_bg">
                                            <div class="bg"  data-bg="images/bg/dec/6.png"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="section-bg">
                            <div class="bg"  data-bg="images/bg/dec/section-bg.png"></div>
                        </div>
                    </section>
        <!--  section end  -->
        <div class="brush-dec2 brush-dec_bottom"></div>
</div>
{% endblock %}