api/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from . import views
app_name = 'api'

urlpatterns = [

    # API
    path('', views.ProductListAPI.as_view(), name='api-menu'),
    path('product/<int:pk>/', views.ProductAPI.as_view(), name='api-product'),
    path('product/list/', views.ProductListAPI.as_view(), name='api-product-list'),
    path('category/list/', views.CategoryListAPI.as_view(), name='api-category-list'),
    path('category/<int:pk>/', views.CategoryAPI.as_view(), name='api-category'),

    # Table
    path('table/view/list/', views.TableViewListAPI.as_view(), name='api-table-view-list'),
    path('table/view/<int:pk>/', views.TableViewAPI.as_view(), name='api-table-view'),

    path('table/people/count/list/', views.TableCountListAPI.as_view(), name='api-table-people-count-list'),
    path('table/people/count/<int:pk>/', views.TableCountAPI.as_view(), name='api-table-people-count'),

    path('table/time/list/', views.TableTimeListAPI.as_view(), name='api-table-time-list'),
    path('table/time/<int:pk>/', views.TableTimeAPI.as_view(), name='api-table-time'),

    # Book Table
    path('table/book/', views.BookTableAPI.as_view(), name='api-table-book'),
    path('booked/table/list/', views.BookedTableListAPIView.as_view(), name='api-book-table-list'),

    # Remove Table
    path('table/remove/', views.RemoveTableOrderAPI.as_view(), name='api-table-remove'),


    # Order API
    path('cart/', views.CartListAPI.as_view(), name='api-cart-list'),
    path('add_to_cart/<slug>/', views.AddToCartAPI.as_view(), name='api-add-to-cart'),
    path('cart/<int:cart_pk>/<int:qty>/',
         views.CartQuantityUpdateAPI.as_view(), name='api-cart-qty-update'),
    path('cart/total/<int:pk>/',
         views.CartTotalAPI.as_view(), name='api-cart-total'),
    path('cart/detail/<int:pk>/',
         views.CartDetailAPI.as_view(), name='api-cart-detail'),

    # Order
    path('list/', views.OrderListAPI.as_view(), name='api-list'),
    path('detail/<int:pk>/', views.OrderDetailAPI.as_view(), name='api-detail'),
    path('order/total/', views.OrderTotalAPI.as_view(), name='api-total'),

    # Cancel Order
    path('cancel/<int:pk>/', views.CancelOrderAPI.as_view(),
         name='api-cancel-order'),
    # Cancel Reason
    path('cancel/reason/', views.OrderCancelReasonAPI.as_view(),
         name='api-cancel-reason'),

    # Coupon
    path('coupon/', views.AddCouponOrderAPI.as_view(), name='api-coupon-order'),

    # Checkout
    path('checkout/', views.CheckoutAPI.as_view(), name='api-checkout'),
    path('payment/<int:pk>/', views.PaymentDetailAPI.as_view(),
         name='api-payment-detail'),

    path('register/', views.RegisterAPI.as_view(), name='api-register'),
    path('login/', views.LoginAPI.as_view(), name='api-login'),

    # Update
    path('user/update/', views.UpdateUpdateAPI.as_view(), name='api-update'),

    # Username Verification
    path('resend-confirmation/<str:email>/', views.ResendEmailConfirmationAPI.as_view(),
         name='api-resend-username-confirmation'),

    # Password
    path('password/change/', views.ChangePasswordAPI.as_view(), name='api-password-change'),
    path('password/reset/', include('django_rest_passwordreset.urls', namespace='api-password-reset')),



    path('order/response/', views.RazorPayResponseView.as_view(), name='api-order-payment-response'),


    path('room/booked/<int:pk>/', views.BookRoomAPI.as_view(), name='api-book-room'),
    path('room/list/', views.RoomListAPI.as_view(), name='api-room-list'),
    path('room/response/', views.PaymentAPIView.as_view(), name='api-payment-response'),
    path('room/booked/list/', views.BookedRoomListViewAPI.as_view(), name='api-booked-room-list'),
    path('room/confirmed/booked/list/', views.ConfirmedBookRoomListView.as_view(), name='api-confirmed-book-room-list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

golden_nest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('letsmanagestuff/', admin.site.urls),
    path('user/', include('users.urls')),
    path('api/', include('api.urls')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('order/', include('order.urls', namespace='order')),
    path('room/', include('room.urls', namespace='room')),
    path('analytics/', include('analytics.urls', namespace='analytics')),
    path('', include('home.urls', namespace='home')),
]


order/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from . import api

app_name = 'order'

urlpatterns = [
    # Cart
    path('cart/', views.CartListView.as_view(), name='cart'),
    path('qr/cart/', views.OfflineCartListView.as_view(), name='cart-qr-code'),
    path('cart/add/<int:pk>/', views.AddtoCart.as_view(), name='add-to-cart'),
    path('qr/cart/add/', views.AddtoCartQR.as_view(), name='add-to-cart-qr-code'),
    path('cart/remove/<pk>/', views.RemoveFromCart.as_view(),
         name='remove-from-cart'),
    path('cart/delete/<pk>/', views.DeleteCart.as_view(), name='delete-cart'),
    path('delete/complete/cart/', views.RemoveAllCart.as_view(), name='delete-all-cart'),
    path('qr/cart/delete/<pk>/', views.DeleteTableCart.as_view(), name='delete-cart-qr-code'),
    path('qr/delete/complete/cart/', views.RemoveAllTableCart.as_view(), name='delete-all-cart-qr-code'),

    # Order
    path('list/', views.OrderListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.OrderDetailView.as_view(), name='detail'),

    # Order Return
    path('cancel/<int:pk>/', views.CancelOrderView.as_view(), name='cancel'),

    # Checkout
    path('coupon/', views.CheckoutCoupon.as_view(), name='coupon'),
    path('coupon/remove/', views.CheckoutCouponRemove.as_view(), name='coupon-remove'),

    # Payment
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('qr/checkout/', views.OfflineCheckoutView.as_view(), name='checkout-qr-code'),
    # path('payment/', views.PaymentView.as_view(), name='payment'),
    path('razorpay/response/', views.RazorPayResponseView.as_view(), name='payment-response'),

    # Rest Api
    # Cart
    path('api/cart/', api.CartListAPI.as_view(), name='api-cart'),
    path('api/add_to_cart/<slug>/', api.AddToCartAPI.as_view(), name='api-cart'),
    path('api/cart/<int:cart_pk>/<int:qty>/',
         api.CartQuantityUpdateAPI.as_view(), name='api-cart-qty-update'),
    path('api/cart/total/<int:pk>/',
         api.CartTotalAPI.as_view(), name='api-cart-total'),
    path('api/cart/detail/<int:pk>/',
         api.CartDetailAPI.as_view(), name='api-cart-detail'),

    # Order
    path('api/list/', api.OrderListAPI.as_view(), name='api-list'),
    path('api/detail/<int:pk>/', api.OrderDetailAPI.as_view(), name='api-detail'),
    path('api/order/total/'
         ''
         ''
         '/', api.OrderTotalAPI.as_view(), name='api-total'),

    # Cancel Order
    path('api/cancel/<int:pk>/', api.CancelOrderAPI.as_view(),
         name='api-cancel-order'),
    # Cancel Reason
    path('api/cancel/reason/', api.OrderCancelReasonAPI.as_view(),
         name='api-cancel-reason'),

    # Coupon
    path('api/coupon/', api.AddCouponOrderAPI.as_view(), name='api-coupon-order'),

    # Checkout
    path('api/checkout/', api.CheckoutAPI.as_view(), name='api-checkout'),
    path('api/payment/<int:pk>/', api.PaymentDetailAPI.as_view(),
         name='api-payment-detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone, dateformat
from datetime import timedelta, datetime
from ckeditor.fields import RichTextField


class RestaurantsTiming(models.Model):
    opening_time = models.TimeField()
    closing_time = models.TimeField()

    def __str__(self):
        return f"Restaurants Timing"

    def is_restaurant_open(self):
        now = datetime.now()
        now = now.strftime('%H:%M:%S')
        return self.opening_time.strftime('%H:%M:%S') < now < self.closing_time.strftime('%H:%M:%S')



class TPP(models.Model):
    tand_c = RichTextField(null=True, blank=True)
    shipping_policy = RichTextField(null=True, blank=True)
    refund_policy = RichTextField(null=True, blank=True)
    return_policy = RichTextField(null=True, blank=True)
    cancellation_policy = RichTextField(null=True, blank=True)
    privacy_policy = RichTextField(null=True, blank=True)

    def __str__(self):
        return 'TPP'


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    mobile = models.BigIntegerField()
    description = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.name}_{self.mobile}"


class UpcomingEvent(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{ self.title }"

room/models.py
from datetime import datetime
import datetime as dt
from math import floor

from django.utils import timezone

from django.db import models
from django.urls import reverse
from users.models import User

REVIEW_RATING_CHOICES = (
    (1.0, 1.0),
    (2.0, 2.0),
    (3.0, 3.0),
    (4.0, 4.0),
    (5.0, 5.0),
)


class PeopleVariation(models.Model):
    no_of_person = models.CharField(max_length=100)
    # no_of_child = models.IntegerField(default=0)

    def _str_(self):
        return f"{self.no_of_person}"


class RoomType(models.Model):
    name = models.CharField(max_length=100)
    image_main = models.ImageField(
        upload_to='room_type', null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.id}"


class Rooms(models.Model):
    name = models.CharField(max_length=100)
    image_main = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    image_2 = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    image_3 = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    image_4 = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    image_5 = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    image_6 = models.ImageField(
        upload_to='rooms', null=True, blank=True)
    stock_no = models.IntegerField(default=0, help_text="Qty of stock!", null=True, blank=True)  # number of products in stock
    # room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True, blank=True)
    people_variation = models.ManyToManyField(PeopleVariation, blank=True)
    price = models.DecimalField(
        max_digits=20, decimal_places=2, null=True, blank=True)
    short_description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.id}"

    def avg_rating(self):
        reviews = self.avgreviews.filter(is_published = True)
        ratings = []
        for review in reviews:
            ratings.append(review.rating)
        try:
            avg = float(floor(sum(ratings) // len(ratings)))
        except ZeroDivisionError:
            avg=0
        return avg


class RoomPayment(models.Model):
    order_id = models.CharField(max_length=200)
    payment_id = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.FloatField()
    amount_paid = models.FloatField()
    paid = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=50)

    razorpay_order_id = models.CharField(max_length=200, null=True, blank=True)
    signature = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.user}_Room Payment"


class RoomBooked(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.BigIntegerField(help_text='Provide an mobile number without +91', null=True, blank=True)
    room_type = models.ForeignKey(
        Rooms, on_delete=models.CASCADE, null=True, blank=True)
    # no_of_room = models.IntegerField(default=1)
    check_in = models.DateField()
    check_out = models.DateField()
    is_booked = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    is_booked_offline = models.BooleanField(default=False)
    is_checked_out = models.BooleanField(default=False)
    no_of_days = models.IntegerField(default=1)
    ordered_date_time = models.DateTimeField(auto_now=True)
    payment = models.ForeignKey(
        RoomPayment, on_delete=models.SET_NULL, null=True, blank=True)
    payment_method = models.CharField(max_length=30, null=True, blank=True)
    people_variation = models.ForeignKey(PeopleVariation, on_delete=models.SET_NULL, null=True)
    is_rejected = models.BooleanField(default=False)

    seen = models.BooleanField(default=False)
    class Meta:
        ordering = ('-check_in',)

    def __str__(self):
        return f"{self.id}"

    def get_total_one_night(self):
        return self.room_type.price

    def get_tax(self):
        total = self.get_sub_total()
        total = total * 12 // 100
        return total

    def get_total(self):
        total = self.get_sub_total()
        return total + self.get_tax()

    def get_sub_total(self):
        return self.room_type.price * self.no_of_days + self.get_tax()

    def is_available_for_cancellation(self):
        now = dt.date.today()
        if (self.check_in - now).days > 0:
            return True
        return False


class ReviewRoom(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Rooms, on_delete=models.SET_NULL, null=True, related_name='avgreviews')
    date = models.DateTimeField(default=timezone.now)

    review_description = models.TextField()
    rating = models.FloatField(choices=REVIEW_RATING_CHOICES, max_length=3)
    is_published = models.BooleanField(default=False)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.rating}_user"

    def get_absolute_url(self):  # Redirect to this link after adding review
        return reverse("")

    class Meta:
        ordering = ['-rating']
        unique_together = ('user', 'product')

order/forms.py
from django import forms

from .models import CouponCustomer


class CouponCustomerForm(forms.ModelForm):

    class Meta:
        model = CouponCustomer
        fields = ('code',)


order/templates/order/cancelorder_form.html
{% extends 'users/account_base.html' %}
{% load crispy_forms_tags %} 
{% block achead %}Cancel Order{% endblock %}
{% block room %}


    <div class="content">
          {% if form.errors %}
            <div  style="padding: 1.8em; background-color:#C19D60; font-size: 1.5em; display: flex; justify-content: center; align-items: center; " class="alert alert-error">
                {% for field in form %}
                  {% if field.errors %}
                    {% for error in field.errors %}
                       <h3 style="color: rgb(255, 51, 51);">{{ error }}</h3>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              {% if form.non_field_errors %}
                <p style="color: rgb(255, 51, 51);">{{ form.non_field_errors }}</p>
              {% endif %}
            </div>
        {% endif %}



        <section style="padding-top: 0; margin-top:0; transform: translateY(-40px)" class="hidden-section big-padding con-sec" data-scrollax-parent="true" id="sec3">
            <div style="padding: 2em; padding-top: 0; margin-top: 0;" class="container">
                <div class="row">
                    <div >
                        <div class="section-title text-align_left">
                            <h2>Cancel Order</h2>
                            <div class="dots-separator fl-wrap"><span></span></div>
                        </div>
                        <div class="text-block ">
                        </div>
                        <div class="contactform-wrap">
                            <div id="message"></div>
                            <!-- <form  class="custom-form" name="contactform" method="post">
                                {% csrf_token %}
                                <fieldset>
                                <div id="message2"></div>
                                    <div class="row">
                                        {% for field in form %}
                                            {% if 'Name:' in field.label_tag %}
                                                <div class="col-sm-6">
                                                    <input type="text" name="name" id="id_name" placeholder="Your Name*" value="{{ field.value }}" required/>
                                                </div>
                                            {% endif %}
                                         {% endfor %}

                                        {% for field in form %}
                                            {% if 'Phone number:' in field.label_tag %}
                                                <div class="col-sm-6">
                                                    <input type="text" name="phone_number" id="id_phone_number" placeholder="Your Phone Number*" value="{{ field.value }}" required/>
                                                </div>
                                            {% endif %}
                                         {% endfor %}
                                    </div>
                                    <div class="clearfix"></div>
                                    <button class="btn float-btn flat-btn color-bg" id="submit_cnt">Update <i class="fal fa-long-arrow-right"></i></button>
                                </fieldset>
                            </form> -->

                            <form class="custom-form" name="cancelorderform" method="post" >
                                {% csrf_token %}
                                <fieldset>
                                <div id="message2"></div>
                                    <div class="row">

                                                <div class="col-sm-12">
                                                    <h3 align="left" style="font-size: 1.4em; margin: 1em 1em 0.7em 0; color: #fff;">Cancel Reason</h3>
                                                    <!-- {% for variation in form.cancel_reason %}
                                                            <option style="background: rgba(39,39,39);" value="{{variation}}">{{variation}}</option>
                                                        {% endfor %} -->
                                                    
                                                    <select class="nice-select chosen-select no-search-select" required id="id_cancel_reason" style="padding: 1.2em 1.5em; margin-bottom:1.5em; background: rgba(255,255,255,0.1); width: 100%;border: 0px;color: white;">
                                                        <option style="background: rgba(39,39,39);" value="Not Needed">Not Needed</option>
                                                        <option style="background: rgba(39,39,39);" value="Ordered Wrong Dishes">Ordered Wrong Dishes</option>
                                                        <option style="background: rgba(39,39,39);" value="Receiving To Late">Receiving To Late</option>
                                                        <option style="background: rgba(39,39,39);" value="Other">Other</option>
                                                    </select>
                                                </div>


                                                <div class="col-sm-12">
                                                    <h3 align="left" style="font-size: 1.4em; margin: 1em 1em 0.7em 0; color: #fff;">Review Description</h3>
                                                    {{form.review_description}}
                                                </div>

                                            
                                    </div>
                                    <div class="clearfix"></div>
                                    <button class="btn float-btn flat-btn color-bg" id="submit_cnt">Submit <i class="fal fa-long-arrow-right"></i></button>
                                </fieldset>
                            </form>
                        </div>
                        <div class="section-dec sec-dec_top"></div>
                    </div>
                </div>
            </div>
            <div class="section-bg">
                <div class="bg"  data-bg="images/bg/dec/section-bg.png"></div>
            </div>
        </section>

        <div class="brush-dec2 brush-dec_bottom"></div>
</div>



{% endblock %}

order/templates/order/offline_order_success.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}


<div class="content">
    <section class="parallax-section hero-section hidden-section big-padding" data-scrollax-parent="true">

        <div style="height: 50vh;" class="container">
            <div style="height: 100%; margin-top: 5em;" class="section-title text-center">
                <h2 style="color: #B09059;"><i class="far fa-check-circle"></i></h2>
                <br>
                <h2>Thank You for Coming</h2>
                <br>
                <h4>Your order placed!</h4>
                <br>
            </div>
        </div>
    </section>

    <section class="hidden-section big-padding" data-scrollax-parent="true">

    </section>
</div>

{% endblock %}

order/templates/order/order.html
{% extends 'users/account_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load l10n %}
{% block achead %}Your Orders{% endblock %}
{% block room %}

{% if not object_list %}
<div style="height: 50vh;" class="container">
    <div style="height: 100%;" class="section-title text-center">
        <img  src="{% static 'home/images/logo/roasted-chicken.png' %}"  style="height: 250px;width: 250px;object-fit: cover;"  alt="logo">
        <h2>No Orders Yet</h2>
        <br>
        <a href="/menu" class="btn color-bg" type="submit">Order Now  <i class="fal fa-long-arrow-right"></i></a>
    </div>
</div>
{% endif %}

{% for order in object_list %}
    {% if order.cart.all %}
<table class="table table-border checkout-table" style="overflow: auto;margin-bottom: 2em;">
    <tbody>
    <tr>
<!--                                <th class="hidden-xs">Item</th>-->
        <th width="50%" style="color: #C19D60;text-align: left;font-family: 'Playfair Display', cursive;font-size: 17px;">
            #{{order.order_ref_number}}
            
        </th>
        <th></th>
        <th style="color: #C19D60;text-align: center;font-family: 'Playfair Display', cursive;font-size: 17px;"></th>
        <th>Status</th>

    </tr>
    {% for object in order.cart.all %}

    <tr>
        <td style="text-align: left;">{{object.product.title}}</td>
        <td>{{object.quantity}}</td>
        <td>₹{{object.get_total_item_price}}</td>
        <td>{% if object.order_status == "Ready" %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-clock"></i>{% endif %}</td>
    </tr>

    {% endfor %}

    <tr>
        <td width="50%" style="color: #C19D60;text-align: left;font-family: 'Playfair Display', cursive;font-size: 15px;">&nbsp;Order Total -</td>
        <td></td>
        <th style="color: #C19D60;text-align: center;font-family: 'Playfair Display', cursive;font-size: 17px;">₹{{order.get_total_without_coupon}}</th>
        <td style="color: #C19D60;">
            <a style="color: #C19D60; " href="{% url 'order:detail' order.pk %}">Manage</a>
            <!-- <a style="color: #C19D60; " href="{% url 'order:detail' order.pk %}"><i class="fas fa-external-link-alt"></i></a> -->
            <!-- {% if object.order_status == "Delivered" %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-clock"></i>{% endif %} -->
        </td>
    </tr>

    </tbody>
</table>
    {% endif %}
{% endfor %}

{% endblock room %}